package com.aquirozc.cconverter.exchange;
public enum Country{

    EMIRATOS_ARABES_UNIDOS("AED", "Dirham de los Emiratos Arabes Unidos"),
    AFGANISTAN("AFN", "Afgani afgano"),
    ALBANIA("ALL", "Lek albanes"),
    ARMENIA("AMD", "Dram armenio"),
    ANTILLAS_NEERLANDESAS("ANG", "Florin antillano neerlandes"),
    ANGOLA("AOA", "Kwanza angoleno"),
    ARGENTINA("ARS", "Peso argentino"),
    AUSTRALIA("AUD", "Dolar australiano"),
    ARUBA("AWG", "Florin arubeno"),
    AZERBAIYAN("AZN", "Manat azeri"),
    BOSNIA_Y_HERZEGOVINA("BAM", "Marco convertible de Bosnia y Herzegovina"),
    BARBADOS("BBD", "Dolar de Barbados"),
    BANGLADES("BDT", "Taka de Banglades"),
    BULGARIA("BGN", "Lev bulgaro"),
    BAHREIN("BHD", "Dinar bahreini"),
    BURUNDI("BIF", "Franco burundes"),
    BERMUDAS("BMD", "Dolar bermudense"),
    BRUNEI("BND", "Dolar de Brunei"),
    BOLIVIA("BOB", "Boliviano boliviano"),
    BRASIL("BRL", "Real brasileno"),
    BAHAMAS("BSD", "Dolar bahameno"),
    BUTAN("BTN", "Ngultrum butanes"),
    BOTSUANA("BWP", "Pula de Botsuana"),
    BELARUS("BYN", "Rublo bielorruso"),
    BELICE("BZD", "Dolar de Belice"),
    CANADA("CAD", "Dolar canadiense"),
    CONGO("CDF", "Franco congoleño"),
    SUIZA("CHF", "Franco suizo"),
    CHILE("CLP", "Peso chileno"),
    CHINA("CNY", "Yuan chino"),
    COLOMBIA("COP", "Peso colombiano"),
    COSTA_RICA("CRC", "Colon costarricense"),
    CUBA("CUP", "Peso cubano"),
    CABO_VERDE("CVE", "Escudo caboverdiano"),
    REPUBLICA_CHECA("CZK", "Corona checa"),
    DJIBOUTI("DJF", "Franco yibutiano"),
    DINAMARCA("DKK", "Corona danesa"),
    REPUBLICA_DOMINICANA("DOP", "Peso dominicano"),
    ARGELIA("DZD", "Dinar argelino"),
    EGIPTO("EGP", "Libra egipcia"),
    ERITREA("ERN", "Nakfa eritreo"),
    ETIOPIA("ETB", "Birr etiope"),
    UNION_EUROPEA("EUR", "Euro"),
    FIJI("FJD", "Dolar fiyiano"),
    ISLAS_MALVINAS("FKP", "Libra malvinense"),
    ISLAS_FEROE("FOK", "Corona feroesa"),
    REINO_UNIDO("GBP", "Libra esterlina"),
    GEORGIA("GEL", "Lari georgiano"),
    GUERNESEY("GGP", "Libra de Guernsey"),
    GHANA("GHS", "Cedi ghanes"),
    GIBRALTAR("GIP", "Libra gibraltarena"),
    GAMBIA("GMD", "Dalasi gambiano"),
    GUINEA("GNF", "Franco guineano"),
    GUATEMALA("GTQ", "Quetzal guatemalteco"),
    GUYANA("GYD", "Dolar guyanes"),
    HONG_KONG("HKD", "Dolar hongkones"),
    HONDURAS("HNL", "Lempira hondureno"),
    CROACIA("HRK", "Kuna croata"),
    HAITI("HTG", "Gourde haitiano"),
    HUNGRIA("HUF", "Forinto hungaro"),
    INDONESIA("IDR", "Rupia indonesia"),
    ISRAEL("ILS", "Nuevo shekel israeli"),
    ISLA_DE_MAN("IMP", "Libra de la Isla de Man"),
    INDIA("INR", "Rupia india"),
    IRAK("IQD", "Dinar iraqui"),
    IRAN("IRR", "Rial irani"),
    ISLANDIA("ISK", "Corona islandesa"),
    JERSEY("JEP", "Libra de Jersey"),
    JAMAICA("JMD", "Dolar jamaiquino"),
    JORDANIA("JOD", "Dinar jordaniano"),
    JAPON("JPY", "Yen japones"),
    KENIA("KES", "Chelin keniano"),
    KIRGUISTAN("KGS", "Som kirguis"),
    CAMBOYA("KHR", "Riel camboyano"),
    KIRIBATI("KID", "Dolar de Kiribati"),
    COMORAS("KMF", "Franco comorense"),
    COREA_DEL_SUR("KRW", "Won surcoreano"),
    KUWAIT("KWD", "Dinar kuwaiti"),
    ISLAS_CAIMAN("KYD", "Dolar de las Islas Caiman"),
    KAZAJISTAN("KZT", "Tenge kazajo"),
    LAOS("LAK", "Kip laosiano"),
    LIBANO("LBP", "Libra libanesa"),
    SRI_LANKA("LKR", "Rupia de Sri Lanka"),
    LIBERIA("LRD", "Dolar liberiano"),
    LESOTO("LSL", "Loti de Lesoto"),
    LIBIA("LYD", "Dinar libio"),
    MARRUECOS("MAD", "Dirham marroqui"),
    MOLDAVIA("MDL", "Leu moldavo"),
    MADAGASCAR("MGA", "Ariary malgache"),
    MACEDONIA_DEL_NORTE("MKD", "Denar macedonio"),
    MYANMAR("MMK", "Kyat birmano"),
    MONGOLIA("MNT", "Togrog mongol"),
    MACAO("MOP", "Pataca de Macao"),
    MAURITANIA("MRU", "Ouguiya mauritana"),
    MAURICIO("MUR", "Rupia mauriciana"),
    MALDIVAS("MVR", "Rufiyaa maldiva"),
    MALAWI("MWK", "Kwacha de Malawi"),
    MEXICO("MXN", "Peso mexicano"),
    MALASIA("MYR", "Ringgit malayo"),
    MOZAMBIQUE("MZN", "Metical mozambiqueño"),
    NAMIBIA("NAD", "Dolar namibio"),
    NIGERIA("NGN", "Naira nigeriana"),
    NICARAGUA("NIO", "Cordoba nicaraguense"),
    NORUEGA("NOK", "Corona noruega"),
    NEPAL("NPR", "Rupia nepali"),
    NUEVA_ZELANDA("NZD", "Dolar neozelandes"),
    OMAN("OMR", "Rial de Oman"),
    PANAMA("PAB", "Balboa panameno"),
    PERU("PEN", "Sol peruano"),
    PAPUA_NUEVA_GUINEA("PGK", "Kina de Papua Nueva Guinea"),
    FILIPINAS("PHP", "Peso filipino"),
    PAKISTAN("PKR", "Rupia paquistani"),
    POLONIA("PLN", "Zloty polaco"),
    PARAGUAY("PYG", "Guarani paraguayo"),
    QATAR("QAR", "Riyal qatarí"),
    RUMANIA("RON", "Leu rumano"),
    SERBIA("RSD", "Dinar serbio"),
    RUSIA("RUB", "Rublo ruso"),
    RUANDA("RWF", "Franco ruandes"),
    ARABIA_SAUDITA("SAR", "Riyal saudí"),
    ISLAS_SALOMON("SBD", "Dolar de las Islas Salomon"),
    SEYCHELLES("SCR", "Rupia de Seychelles"),
    SUDAN("SDG", "Libra sudanesa"),
    SUECIA("SEK", "Corona sueca"),
    SINGAPUR("SGD", "Dolar singapurense"),
    ISLA_DE_SANTA_HELENA("SHP", "Libra de Santa Helena"),
    SIERRA_LEONA("SLE", "Leone sierraleones"),
    SOMALIA("SOS", "Chelin somali"),
    SURINAM("SRD", "Dolar surinamense"),
    SUDAN_DEL_SUR("SSP", "Libra de Sudan del Sur"),
    SAO_TOME_Y_PRINCIPE("STN", "Dobra de Sao Tome y Principe"),
    SIRIA("SYP", "Libra siria"),
    ESWATINI("SZL", "Lilangeni swazi"),
    TAILANDIA("THB", "Baht tailandes"),
    TAYIKISTAN("TJS", "Somoni tayiko"),
    TURKMENISTAN("TMT", "Manat turcomano"),
    TUNEZ("TND", "Dinar tunecino"),
    TONGA("TOP", "Paanga tongana"),
    TURQUIA("TRY", "Lira turca"),
    TRINIDAD_Y_TOBAGO("TTD", "Dolar de Trinidad y Tobago"),
    TUVALU("TVD", "Dolar de Tuvalu"),
    TAIWAN("TWD", "Nuevo dolar taiwanes"),
    TANZANIA("TZS", "Chelin tanzano"),
    UCRANIA("UAH", "Grivna ucraniana"),
    UGANDA("UGX", "Chelin ugandes"),
    ESTADOS_UNIDOS("USD", "Dolar estadounidense"),
    URUGUAY("UYU", "Peso uruguayo"),
    UZBEKISTAN("UZS", "Som uzbeko"),
    VENEZUELA("VES", "Bolivar venezolano"),
    VIETNAM("VND", "Dong vietnamita"),
    VANUATU("VUV", "Vatu de Vanuatu"),
    SAMOA("WST", "Tala samoano"),
    CEMAC("XAF", "Franco CFA de Africa Central"),
    ORGANIZACION_DE_ESTADOS_DEL_CARIBE_ORIENTAL("XCD", "Dolar del Caribe Oriental"),
    FONDO_MONETARIO_INTERNACIONAL("XDR", "Derechos Especiales de Giro"),
    CFA("XOF", "Franco CFA de Africa Occidental"),
    COLECTIVIDADES_DE_ULTRAMAR("XPF", "Franco CFP"),
    YEMEN("YER", "Rial yemeni"),
    SUDAFRICA("ZAR", "Rand sudafricano"),
    ZAMBIA("ZMW", "Kwacha zambiano"),
    ZIMBABUE("ZWL", "Dolar zimbabuense");

    public final String ISO4217Code;
    public final String currencyName;    

    private Country(String ISO4217Code, String currencyName){
        this.ISO4217Code = ISO4217Code;
        this.currencyName = currencyName;
    }

    @Override
    public String toString() {
        return String.format("%s (%s)", currencyName, ISO4217Code);
    }
    
}
